name: currancy_converter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"  # Ensure this path exists
  adaptive_icon_background: "#ffffff"  # Background color (for Android)
  adaptive_icon_foreground: "assets/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/app_icon.png  # Ensure the asset is correctly referenced
    - assets/background.jpg
